# from https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release
name: Check Latest Manim CE Version
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Fetch release version
        run: |
          # save version from json in file
          curl -sL https://api.github.com/repos/ManimCommunity/manim/releases/latest | \
          jq -r ".tag_name" > release_versions/manim_ce_latest.txt

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Christopher Besch'
          git config --global user.email 'christopher.besch@gmx.de'
          git commit -am "New Manim CE release version"
          git push
