name: Linux Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Debug",
            artifact: "linux_debug.tar.xz",
            build_type: "build_debug",
            quality: "ql",
            push_to_pages: false
          }
          - {
            name: "Release",
            artifact: "linux_release.tar.xz",
            build_type: "build_release",
            quality: "qh",
            push_to_pages: true
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Update environment
        run: |
          sudo apt install libcairo2-dev libpango1.0-dev ffmpeg python3-pip nodejs npm
          pip3 install -r requirements.txt
          cd ${{github.workspace}}/web
          npm install
          cd ${{github.workspace}}

      - name: Build Web
        run: |
          cd ${{github.workspace}}/web
          npm run ${{matrix.config.build_type}}
          cd ${{github.workspace}}

      - name: Test
        run: |
          manim example.py "-${{matrix.config.quality}}" --write_all

      - name: Deploy to GitHub Pages
        if: matrix.config.push_to_pages && success()
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: presentation

      - name: Prepare Upload
        run: |
          tar cfz ${{matrix.config.artifact}} presentation

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{matrix.config.artifact}}
          name: ${{matrix.config.artifact}}
